### ISSUE TITLE
simulate_python unitree_mujoco.py RuntimeError: can't create new thread at interpreter shutdown

### ISSUE THREAD

**Issue by sdhou** [unitreerobotics/unitree_mujoco#30]
Running unitree_mujoco.py fails with the following message Need help Thanks!

python unitree_mujoco.py
pygame 2.6.1 (SDL 2.28.4, Python 3.12.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
Exception in thread Thread-4 (SimulationThread):
Traceback (most recent call last):
  File "/home/westwell/miniconda3/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/home/westwell/miniconda3/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/code/unitree_mujoco/simulate_python/unitree_mujoco.py", line 42, in SimulationThread
    unitree = UnitreeSdk2Bridge(mj_model, mj_data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/unitree_mujoco/simulate_python/unitree_sdk2py_bridge.py", line 66, in __init__
    self.lowStateThread.Start()
  File "/opt/code/unitree_sdk2_python/unitree_sdk2py/utils/thread.py", line 20, in Start
    return self.__thread.start()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/westwell/miniconda3/lib/python3.12/threading.py", line 992, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't create new thread at interpreter shutdown

python                    3.12.2
unitree_mujoco      main
mujoco                    3.2.5
pygame                    2.6.1
cyclonedds             releases/0.10.x

**Comment by sdhou** [comment]
Problem solved after switching python version to 3.10 and  Installing from source unitree_sdk2_python.
